name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
  
permissions:
  contents: read
  pull-requests: write
  
jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Spell Check
        uses: check-spelling/check-spelling@v0.0.24
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          extra_dictionaries: |
            cspell:software-terms/dict/softwareTerms.txt
            cspell:node/dict/node.txt
            cspell:npm/dict/npm.txt
            cspell:php/dict/php.txt
            cspell:python/src/python/python-lib.txt
