# Typos configuration file

[default]
extend-ignore-re = [
  # Add regex patterns to ignore specific cases here
]

[files]
extend-exclude = [
  # Add filenames or patterns to exclude from checking
  "package.json",
  "package-lock.json",
  "node_modules/",
  "next.config.mjs",
  "mdx-components.js",
  "app"
]
